name: Lint

on: pull_request

jobs:
  echo-changed-files:
    name: Echo changed files
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Branch Name
        run: |
          echo Base branch ${{ github.base_ref }}
          echo Source branch ${{ github.head_ref }}
      
      - name: list files
        id: changed_files
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename' | grep  -E '(.js$|.ts$|.tsx$)'))
          echo $FILES
          if [[ -z ${FILES} ]]; then
            echo "::set-output name=files_changed::true"
            echo "::set-output name=file_names::${FILES}"
          else
            echo "no script file changed!!"
            echo "::set-output name=files_changed::false"
          fi

      # - name: Find changed files.
      #   id: changed_files
      #   run: |
      #     npm run sample1

      - name: Perform action if files changed.
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          echo "changed files ${{steps.changed_files.outputs.file_names}}"
